# Default Profile
#spring:
#    profiles:
#        active: h2
server:
    error:
        include-message: always

logging:
    level:
        root: INFO
        com.footballstore.apparels: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Profile: h2 (Local Development)
spring:
    config:
        activate:
            on-profile: h2
    datasource:
        url: jdbc:h2:mem:apparels-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,VALUE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true
    sql:
        init:
            platform: h2
            mode: always
server:
    port: 8080

---
# Profile: docker (PostgreSQL)
spring:
    config:
        activate:
            on-profile: docker
    datasource:
        url: jdbc:postgresql://postgres1/apparels-db
        username: user
        password: pwd
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQLDialect
                    auto-quote-keyword: true
        defer-datasource-initialization: true
    sql:
        init:
            platform: psql
            mode: always
            schema-locations: "classpath:/schema-psql.sql"
server:
    port: 8080