# Default Profile
#spring:
#    profiles:
#        active: h2
server:
    error:
        include-message: always

logging:
    level:
        root: INFO
        com.footballstore.customers: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
# Profile: h2 (Local Development)
spring:
    config:
        activate:
            on-profile: h2
    datasource:
        url: jdbc:h2:mem:customers-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,VALUE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true
    sql:
        init:
            platform: h2
            mode: always
server:
    port: 8080

---
# Profile: docker (MySQL)
spring:
    config:
        activate:
            on-profile: docker
    datasource:
        url: jdbc:mysql://mysql1/customers-db
        username: user
        password: pwd
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        defer-datasource-initialization: true
    sql:
        init:
            platform: mysql
            mode: always
server:
    port: 8080
